# Generated by Django 4.2.8 on 2024-01-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BRNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('1', '법률'), ('2', '규정'), ('3', '규제지침')], max_length=2)),
                ('nation', models.CharField(max_length=10)),
                ('doc_id', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='brnc/')),
            ],
        ),
        migrations.CreateModel(
            name='UNIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(choices=[('1', 'Safety Context'), ('2', '안전전략'), ('3', '부지 특성'), ('4', '처분장 설계'), ('5', '안전성 평가 방법론'), ('6', '운영 중 안전성 평가'), ('7', '폐쇄 후 안전성 평가'), ('8', '관리 시스템/이해관계자 및 규제기관 참여'), ('9', '증거들의 종합'), ('10', '불확실성 관리'), ('11', '한계점, 통제 및 조건')], max_length=20)),
                ('eval1', models.CharField(default='1', max_length=2)),
                ('epg', models.BooleanField(default=False)),
                ('develop', models.CharField(choices=[('1', '개념화'), ('2', '부지조사/선정'), ('3', '기준 설계/인허가 신청'), ('4', '건설'), ('5', '운영'), ('6', '폐쇄')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=10)),
                ('background', models.TextField()),
                ('regulation', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='unist/')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=10)),
                ('report_title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='unist/report/')),
                ('case_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kinsdb.unist')),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reviewed', models.CharField(max_length=200)),
                ('section_reviewed', models.CharField(max_length=200)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_report', to='kinsdb.report')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('proposal', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='kinsdb.report')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('index', models.CharField(max_length=100)),
                ('index_title', models.CharField(max_length=200)),
                ('index_title_kr', models.CharField(max_length=200)),
                ('index_content', models.TextField()),
                ('index_content_kr', models.TextField()),
                ('sector', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_doc', to='kinsdb.brnc')),
            ],
            options={
                'ordering': ('brnc__doc_id', 'title', 'index'),
            },
        ),
    ]
