# Generated by Django 4.2.8 on 2024-01-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brnc',
            name='doc_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brnc',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='index_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='index_title_kr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='related',
            name='report_reviewed',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
