# Generated by Django 4.2.8 on 2024-01-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0002_alter_brnc_doc_id_alter_brnc_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brnc',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
