# Generated by Django 4.2.8 on 2024-01-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0003_alter_brnc_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brnc',
            name='system',
            field=models.CharField(choices=[('1', '법률'), ('2', '규정'), ('3', '규제지침')], max_length=2),
        ),
    ]
