# Generated by Django 4.2.8 on 2024-01-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0007_rename_evaluation_unist_assessment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unist',
            name='epg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
