# Generated by Django 4.2.8 on 2024-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0008_unist_epg'),
    ]

    operations = [
        migrations.AddField(
            model_name='unist',
            name='assessment3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
