# Generated by Django 4.2.8 on 2024-01-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0010_rename_assessment1_unist_evluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unist',
            name='epg',
            field=models.BooleanField(default=False),
        ),
    ]
