# Generated by Django 4.2.8 on 2024-01-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0013_alter_unist_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unist',
            name='eval2',
        ),
        migrations.AlterField(
            model_name='unist',
            name='eval1',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='unist',
            name='evaluation',
            field=models.CharField(choices=[('01', 'Safety Context'), ('02', '안전전략'), ('03', '부지 특성'), ('04', '처분장 설계'), ('05', '안전성 평가 방법론'), ('06', '운영 중 안전성 평가'), ('07', '폐쇄 후 안전성 평가'), ('08', '관리 시스템/이해관계자 및 규제기관 참여'), ('09', '증거들의 종합'), ('10', '불확실성 관리'), ('11', '한계점, 통제 및 조건')], max_length=20),
        ),
    ]
