# Generated by Django 4.2.8 on 2024-02-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
