# Generated by Django 4.2.8 on 2024-01-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
