# Generated by Django 4.2.8 on 2024-01-26 05:38

import cloud.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='admin', max_length=10)),
                ('institute', models.CharField(choices=[('1', 'KINS'), ('2', 'NCS'), ('3', 'UNIST'), ('4', 'BRNC')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('1', 'N/Star'), ('2', '논문'), ('3', '보고서'), ('4', '일정')], max_length=2)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached', models.FileField(blank=True, null=True, upload_to=cloud.models.get_file_path, verbose_name='file')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='filename')),
                ('content_type', models.CharField(max_length=128, null=True, verbose_name='MIME TYPE')),
                ('size', models.IntegerField(null=True, verbose_name='file size')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cloud.post', verbose_name='Post')),
            ],
        ),
    ]
