# Generated by Django 4.2.8 on 2023-12-20 10:05

import cloud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_alter_document_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attached',
            field=models.FileField(blank=True, null=True, upload_to=cloud.models.get_file_path, verbose_name='file'),
        ),
    ]
