name: Deployment

on: [push]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-20.04

    steps:
    - name: SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port : 22
        script: |
          cd /home/nctest/projects/MyBoard 

          git pull
          
          source ~/.virtualenvs/venv/bin/activate
          
          pip install -r requirements.txt

          python manage.py collectstatic --no-input
          python manage.py makemigrations
          python manage.py migrate

          sudo systemctl restart uwsgi
