name: Deployment

on: [push]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-20.04

    steps:
    - name: SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port : 22
        script: |
          cd /home/nctest/projects/MyBoard

          git pull
          echo "New changes copied to server"

          source ~/.virtualenvs/venv/bin/activate
          echo "Virtual environment 'venv' activated"
          
          echo "Installing required packages"
          pip install -r requirements.txt

          echo "Gathering static files"
          python manage.py collectstatic --no-input

          echo "Running database migration"
          python manage.py makemigrations
          python manage.py migrate
          

          "Restarting application"
          sudo systemctl restart uwsgi
