name: Django CD

on:
  workflow_run:
    workflows: [ "Django CI" ]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: SSH Connection Test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PEM }}
          port: 22
          script: |
            cd /home/nctest/projects/MyBoard
            git pull
            sudo systemctl restart uwsgi
