name: Deployment

on: [push]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-20.04

    steps:
    - name: SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port : 22
        script: |
          cd /home/nctest/projects/MyBoard
          workon venv
          git pull
          python manage.py migrate
          python manage.py collectstatics --no-input
          sudo systemctl restart uwsgi
          echo "successfully updated"
